common:
  public_key: pk
  private_keys: [sk0, sk1, sk2,sk3] # 
  N: 4
  f: 1

binaryaggrement:
  server0:
    host: 127.0.0.1
    port: 4001
    sessionid: session0
    localid: 0
    coin_rpc: tcp://127.0.0.1:4000
    broadcast_channels: ["tcp://127.0.0.1:4011","tcp://127.0.0.1:4021","tcp://127.0.0.1:4031"]
  server1:
    host: 127.0.0.1
    port: 4011
    sessionid: session1
    localid: 1
    coin_rpc: tcp://127.0.0.1:4010
    broadcast_channels: ["tcp://127.0.0.1:4001","tcp://127.0.0.1:4021","tcp://127.0.0.1:4031"]
  server2:
    host: 127.0.0.1
    port: 4021
    sessionid: session2
    localid: 2
    coin_rpc: tcp://127.0.0.1:4020
    broadcast_channels: ["tcp://127.0.0.1:4001","tcp://127.0.0.1:4011","tcp://127.0.0.1:4031"]
  server3:
    host: 127.0.0.1
    port: 4031
    sessionid: session3
    localid: 3
    coin_rpc: tcp://127.0.0.1:4030
    broadcast_channels: ["tcp://127.0.0.1:4001","tcp://127.0.0.1:4011","tcp://127.0.0.1:4021"]


commoncoin:
  instance_id: sidA
  server0:
    id: 0
    host: 127.0.0.1
    port: 4000
    channels: ["tcp://127.0.0.1:4010","tcp://127.0.0.1:4020","tcp://127.0.0.1:4030"]
  server1:
    id: 1
    host: 127.0.0.1
    port: 4010
    channels: ["tcp://127.0.0.1:4000","tcp://127.0.0.1:4020","tcp://127.0.0.1:4030"]
  server2:
    id: 2
    host: 127.0.0.1
    port: 4020
    channels: ["tcp://127.0.0.1:4000","tcp://127.0.0.1:4010","tcp://127.0.0.1:4030"]
  server3:
    id: 3
    host: 127.0.0.1
    port: 4030
    channels: ["tcp://127.0.0.1:4000","tcp://127.0.0.1:4010","tcp://127.0.0.1:4020"]
