common:
  public_key: pk
  private_keys: [sk0, sk1, sk2,sk3] # 
  N: 4
  f: 1

rbc:
  server0:
    sid: s0
    pid: 0
    broadcast_channels: [[1,"tcp://127.0.0.1:2010"],[2,"tcp://127.0.0.1:2020"],[3,"tcp://127.0.0.1:2030"]]
    host: 127.0.0.1
    port: 2000
  server1:
    sid: s1
    pid: 1
    broadcast_channels: [[0,"tcp://127.0.0.1:2000"],[2,"tcp://127.0.0.1:2020"],[3,"tcp://127.0.0.1:2030"]] # pid,address
    host: 127.0.0.1
    port: 2010
  server2:
    sid: s2
    pid: 2
    broadcast_channels: [[1,"tcp://127.0.0.1:2010"],[0,"tcp://127.0.0.1:2000"],[3,"tcp://127.0.0.1:2030"]]
    host: 127.0.0.1
    port: 2020
  server3:
    sid: s3
    pid: 3
    broadcast_channels: [[1,"tcp://127.0.0.1:2010"],[2,"tcp://127.0.0.1:2020"],[0,"tcp://127.0.0.1:2000"]]
    host: 127.0.0.1
    port: 2030